sudo: false

language: python

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

addons:
  apt:
    packages:
    - sox

# command to install dependencies
install:
  - pip install coveralls
  - pip install pysoundfile
  - pip install -e .

# command to run tests
script: nosetests --with-coverage --cover-erase --cover-package=sox -v -w tests/

after_success:
    - coveralls
    - pip uninstall -y sox

after_failure:
    - pip uninstall -y sox
